### ISSUE TITLE
Paper Download Address Shows 404

### ISSUE THREAD

**Issue by txctxc** [JuRenGithub/HomNet#2]
Dear JuRen,
I love this work, and I am looking forward to seeing the details in the paper.
However, the download address of the paper https://yangy.org/works/application/KDD24_Chromosome.pdf shows 404 and cannot be opened. Could you provide other download methods such as network disk links?
![image](https://github.com/JuRenGithub/HomNet/assets/53358372/2ffe367b-3de4-4501-96b3-6938d63cbe38)

Best wishes!

**Comment by JuRenGithub** [comment]
We've updated it. Please try the link we provided in the readme again.

**Comment by txctxc** [comment]
Thanks!(｡♥‿♥｡)
